CREATE SCHEMA IF NOT EXISTS beer;
CREATE TABLE IF NOT EXISTS beer (
	id	BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	ingredients	VARCHAR(100),
	alcoholContent VARCHAR(10),
	price DECIMAL(10,2) NOT NULL,
	category VARCHAR(20)
);